function plot_intersection(r, offset_x, text_str, color)

if nargin < 4
    color = 'k';
end

% Plot the point
plot3(r(1), r(2), r(3), 'k.', ...
    'MarkerSize', 25, ...
    'LineWidth', 2, ...
    'Color', color, ...
    'HandleVisibility', 'off');
hold on

% Create the label
h = text(r(1) + offset_x, r(2) + offset_x, r(3) + offset_x, text_str, ...
    'FontSize', 12, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'BackgroundColor', 'w', ...
    'Margin', 2, ...
    'Clipping', 'off');   % <-- prevents hiding

% Force it to render on top
uistack(h, 'top');

end