function [consts, mu_altaira, planet_data] = load_planet_data()

    consts = struct('AU', 149597870.691,... % [km]
        'day_s', 86400,...                  % [s]
        'year_s', 365.25 * 86400 ...        % [s]
        );

    mu_altaira = 139348062043.343; % [km^3 s^-2]

    planet_data = readtable("gtoc13_planets.csv");
    planet_data = renamevars(planet_data, { ...
        'x_PlanetID', ...
        'GM_km3_s2_', ...
        'Radius_km_', ...
        'Semi_MajorAxis_km_', ...
        'Eccentricity__', ...
        'Inclination_deg_', ...
        'LongitudeOfTheAscendingNode_deg_', ...
        'ArgumentOfPeriapsis_deg_', ...
        'MeanAnomalyAtT_0_deg_'}, { ...
        'ID',...
        'mu',...
        'radius_km',...
        'a_km', ...
        'e', ...
        'i_deg', ...
        'RAAN_deg', ...
        'w_deg', ...
        'theta0_deg'
    });
end